[package]
name = "muropeptide"
version = "0.1.0"
edition = "2021"

[dependencies]
polychem = { path = "../polychem" }

[lints.rust]
# FIXME: Uncomment this!
# missing_docs = "warn"
# FIXME: Get rid of this!
dead_code = "allow"
