[package]
name = "nom-miette"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
getrandom = { version = "0.2", features = ["js"] }
miette = "7.2.0"
nom = "7.1.3"
thiserror = "1.0.58"

[lints]
workspace = true
