[package]
name = "nom-miette"
version = "0.1.0"
edition = "2021"

[dependencies]
# miette = "6.0.1"
miette = { git = "https://github.com/TheLostLambda/miette" }
nom = "7.1.3"
thiserror = "1.0.57"

[lints.rust]
# FIXME: Uncomment this!
# missing_docs = "warn"
